import "../../../node_modules/bootstrap/scss/bootstrap.scss"
import '../../styles/styles.scss'
import './services.scss'
import '../../components/header/header.scss'
import '../../components/breadCrumbs/breadCrumbs.scss'
import '../../components/mainList/mainList.scss'
import '../../components/secondaryList/secondaryList.scss'
import '../../components/consultation/consultation.scss'
import '../../components/footer/footer.scss'
